# Generated by Django 5.1.7 on 2025-04-24 07:41

import django.db.models.deletion
import polls.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AltriSuggerimenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(help_text='Descrivi il tuo suggerimento.')),
                ('stato', models.CharField(choices=[('non_visualizzato', 'Non visualizzato'), ('valutazione', 'In corso di valutazione'), ('respinto', 'Respinto'), ('lavorazione', 'In lavorazione'), ('attuato', 'Attuato'), ('non_valido', 'Non valido')], default='non_visualizzato', help_text='Stato del suggerimento.', max_length=20)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioDaTradurre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_audio', models.CharField(help_text='ATTENZIONE: RIMUOVERE UN AUDIO RIMUOVE TUTTI I TESTI COLLEGATI AD ESSO (trascrizioni, traduzioni, correzioni).', max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='Data audio')),
                ('file', models.FileField(upload_to='audio_files/', validators=[polls.models.validate_audio_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('modalita', models.CharField(choices=[('tiny', 'Veloce'), ('small', 'Lenta')], default='tiny', help_text='Modalità di traduzione  (Veloce è meno precisa, per un audio di circa 10s richiede ~6s. Lenta è più precisa ma per uno stesso audio richiede ~25s).', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='AudioDaTrascrivere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_audio', models.CharField(help_text='ATTENZIONE: RIMUOVERE UN AUDIO RIMUOVE TUTTI I TESTI COLLEGATI AD ESSO (trascrizioni, traduzioni, correzioni).', max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='Data audio')),
                ('file', models.FileField(upload_to='audio_files/', validators=[polls.models.validate_audio_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('modalita', models.CharField(choices=[('tiny', 'Veloce'), ('small', 'Lenta')], default='tiny', help_text='Modalità di trascrizione  (Veloce è meno precisa, per un audio di circa 10s richiede ~6s. Lenta è più precisa ma per uno stesso audio richiede ~25s).', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SuggerimentiNuoveFunzioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(help_text='Descrivi il tuo suggerimento.')),
                ('stato', models.CharField(choices=[('non_visualizzato', 'Non visualizzato'), ('valutazione', 'In corso di valutazione'), ('respinto', 'Respinto'), ('lavorazione', 'In lavorazione'), ('attuato', 'Attuato'), ('non_valido', 'Non valido')], default='non_visualizzato', help_text='Stato del suggerimento.', max_length=20)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuggerimentiNuoviStrumenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(help_text='Descrivi il tuo suggerimento.')),
                ('stato', models.CharField(choices=[('non_visualizzato', 'Non visualizzato'), ('valutazione', 'In corso di valutazione'), ('respinto', 'Respinto'), ('lavorazione', 'In lavorazione'), ('attuato', 'Attuato'), ('non_valido', 'Non valido')], default='non_visualizzato', help_text='Stato del suggerimento.', max_length=20)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuggerimentiStile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(help_text='Descrivi il tuo suggerimento.')),
                ('stato', models.CharField(choices=[('non_visualizzato', 'Non visualizzato'), ('valutazione', 'In corso di valutazione'), ('respinto', 'Respinto'), ('lavorazione', 'In lavorazione'), ('attuato', 'Attuato'), ('non_valido', 'Non valido')], default='non_visualizzato', help_text='Stato del suggerimento.', max_length=20)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestiScritti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('testo', models.TextField(help_text='ATTENZIONE: Modificare manualmente un testo scritto di cui si è già creato la correzione e salvarlo con la funzione di correzione automatica attiva non sovrascriverà la correzione originale ma ne creerà un altra')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('correggi_automaticamente', models.BooleanField(default=False, help_text='Funzionante solo per testi in lingua italiana. ATTENZIONE: Impossibile creare una correzione su un Testo Scritto in creazione. Per creare una correzione salvare il nuovo testo SENZA la funzione di correzione automatica attiva, aprirlo, attivare la funzione e salvare')),
            ],
        ),
        migrations.CreateModel(
            name='LogAttività',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorrezioniTestiScritti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo_originale', models.TextField(editable=False)),
                ('testo_corretto', models.TextField(blank=True, editable=False, null=True)),
                ('data_creazione_correzione', models.DateTimeField(auto_now_add=True)),
                ('testo_scritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correzioni', to='polls.testiscritti')),
            ],
        ),
        migrations.CreateModel(
            name='Traduzioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo_tradotto', models.TextField(help_text='ATTENZIONE: Modificare manualmente una traduzione di cui si è già creato la correzione e salvarla con la funzione di correzione automatica attiva non sovrascriverà la correzione originale ma ne creerà un altra')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('correggi_automaticamente', models.BooleanField(default=False)),
                ('traduzione_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.audiodatradurre')),
            ],
        ),
        migrations.CreateModel(
            name='CorrezioniTraduzioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo_originale', models.TextField(editable=False)),
                ('testo_corretto', models.TextField(blank=True, editable=False, null=True)),
                ('data_creazione_correzione', models.DateTimeField(auto_now_add=True)),
                ('traduzione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correzioni', to='polls.traduzioni')),
            ],
        ),
        migrations.CreateModel(
            name='Trascrizioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_trascritto', models.TextField(help_text='ATTENZIONE: Modificare manualmente una trascrizione di cui si è già creato la correzione e salvarla con la funzione di correzione automatica attiva non sovrascriverà la correzione originale ma ne creerà un altra')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('correggi_automaticamente', models.BooleanField(default=False)),
                ('trascrizione_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.audiodatrascrivere')),
            ],
        ),
        migrations.CreateModel(
            name='CorrezioniTrascrizioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo_originale', models.TextField(editable=False)),
                ('testo_corretto', models.TextField(blank=True, editable=False, null=True)),
                ('data_creazione_correzione', models.DateTimeField(auto_now_add=True)),
                ('trascrizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correzioni', to='polls.trascrizioni')),
            ],
        ),
    ]
